### ISSUE TITLE
Add tag for version 1.0.0 in Git

### ISSUE THREAD

**Issue by sschuberth** [stevenvachon/isurl#4]
Please tag at least version 1.0.0 in Git, or at best also all other alpha versions that have been released to NPM.

**Comment by stevenvachon** [comment]
Why?

**Comment by sschuberth** [comment]
Because otherwise users don't know which state of the source code belongs to which released package version, which is important for Open Source provenance. Also, tagging releases is common engineering best practice.

**Comment by stevenvachon** [comment]
Master branch is commonly a trunk, except in continuous delivery setups. I don't think it's worth the extra maintenance on a library of this size to have tags. If someone is curious of the state of master branch, they can view the [commits](https://github.com/stevenvachon/isurl/commits/master) to see that it's ahead of a release commit.

**Comment by sschuberth** [comment]
> I don't think it's worth the extra maintenance on a library of this size to have tags.

Thanks for this 😆 You really made my day, confirming my view on the Node community.

> If someone is curious of the state of master branch

FYI, it's not about humans, it's about being able to perform automated license scans on the source code of open source dependencies.

**Comment by stevenvachon** [comment]
> Thanks for this 😆 You really made my day, confirming my view on the Node community.

Do you write machine code by hand? Some things can be considered excessive.

> it's about being able to perform automated license scans on the source code of open source dependencies.

If the current state of the license is required, master branch will do. If the released state of the license is required, the license file is contained within the published package.

**Edit:** There's even the `license` field in the package.json file.

**Comment by pravi** [comment]
There is another reason, to be able to run tests when building a Debian package. If you include tests in the npm registry tarball, that is also another option. Now we have to manually copy test.js to the Debian source package to run tests, which means we have to do extra manual work for every release. It is very easy to miss such a step since it is non standard.
